STRINGS.ACTIONS.HUG = "HUG"

-------------------------------------------------------------------

STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILSON.HUGGER = "Mr. Science might just be checking the other person's heart rate and body temperature."
--STRINGS.CHARACTERS.WILSON.DESCRIBE.WILSON.HUGGER = ""
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WILSON.HUGGER = "Ha ha, don't let your stubble scrape the other person's skin."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WILSON.HUGGER = "The young man needs more exercise to better protect others."
STRINGS.CHARACTERS.WENDY.DESCRIBE.WILSON.HUGGER = "So what, the other person will eventually leave you."
STRINGS.CHARACTERS.WX78.DESCRIBE.WILSON.HUGGER = "Inefficient energy transfer method."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WILSON.HUGGER = "Of course, hugging has a scientific basis for deepening friendships."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WILSON.HUGGER = "If you studied more on how to make trees easier for me to chop down, hugging would be fine."
--STRINGS.CHARACTERS.WES.DESCRIBE.WILSON.HUGGER = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WILSON.HUGGER = "That's not gentlemanly behavior, and don't come to me."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WILSON.HUGGER = "A cunning strategist, building warrior friendship through hugs."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WILSON.HUGGER = "We like to hug the gentleman with the exaggerated hairstyle."
STRINGS.CHARACTERS.WINONA.DESCRIBE.WILSON.HUGGER = "Hugs can improve work efficiency, which is great."
STRINGS.CHARACTERS.WARLY.DESCRIBE.WILSON.HUGGER = "Only love and food should not be wasted, this is a very thoughtful move, sir."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.WILSON.HUGGER = "I wonder if I suddenly jump in, it would startle them, that would be fun."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WILSON.HUGGER = "Smart hug, good."
STRINGS.CHARACTERS.WURT.DESCRIBE.WILSON.HUGGER = "Well, hugging scaleless beings isn't bad either, Plorg."
STRINGS.CHARACTERS.WALTER.DESCRIBE.WILSON.HUGGER = "Hugs can restore friends' courage, this is very scientific, sir."
STRINGS.CHARACTERS.WANDA.DESCRIBE.WILSON.HUGGER = "Well, it's nice, but please pay attention to others' time."

-------------------------------------------------------------------
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WILLOW.HUGGER = "%s finds it hard to contain the flame within, wanting to pass it on to the other person."
--STRINGS.CHARACTERS.WILSON.DESCRIBE.WILLOW.HUGGER = ""
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WILLOW.HUGGER = "Hey! I only like hugging warm flames, not people with body heat."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WILLOW.HUGGER = "%s is a fiery child."
STRINGS.CHARACTERS.WENDY.DESCRIBE.WILLOW.HUGGER = "Only hugging Abigail can ignite the flame in my heart."
STRINGS.CHARACTERS.WX78.DESCRIBE.WILLOW.HUGGER = "Fire human trying to ignite another fire human."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WILLOW.HUGGER = "Ah ha, %s finally realizes that warmth between friends is better than fire?"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WILLOW.HUGGER = "Miss %s's enthusiasm is hard to refuse."
--STRINGS.CHARACTERS.WES.DESCRIBE.WILLOW.HUGGER = ""

STRINGS.CHARACTERS.WALTER.DESCRIBE.WENDY.HUGGER = "Our mission includes guarding the kind lady's true heart, don't you think, Woby!"
STRINGS.CHARACTERS.WANDA.DESCRIBE.WENDY.HUGGER = "I can't remember the last time I opened my heart like this, but I still feel very warm."


STRINGS.CHARACTERS.GENERIC.DESCRIBE.WX78.HUGGER = "It's rare for the heartless %s to make such a human-like gesture."
--STRINGS.CHARACTERS.WILSON.DESCRIBE.WX78.HUGGER = ""
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WX78.HUGGER = "Interesting, who taught this metal dummy to imitate humans?"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WX78.HUGGER = "You're a good robot, even though you're a robot."
STRINGS.CHARACTERS.WENDY.DESCRIBE.WX78.HUGGER = "I guess it's just the boring program making it do this."
STRINGS.CHARACTERS.WX78.DESCRIBE.WX78.HUGGER = "Program error."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WX78.HUGGER = "%s might have read books on how to get along with humans, which is great."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WX78.HUGGER = "He's full of the smell of oil, maybe he doesn't know what he's doing."
--STRINGS.CHARACTERS.WES.DESCRIBE.WX78.HUGGER = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WX78.HUGGER = "Robots are made to serve humans."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WX78.HUGGER = "Iron warrior, do you realize the noble meaning behind your actions?"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WX78.HUGGER = "We fear the gears on %s's body, they might pull out our hair, it hurts."
STRINGS.CHARACTERS.WINONA.DESCRIBE.WX78.HUGGER = "I remember %s pulled off a part of his component, perhaps he doesn't understand the meaning of doing so."
STRINGS.CHARACTERS.WARLY.DESCRIBE.WX78.HUGGER = "%s is a robot friend with noble virtues."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.WX78.HUGGER = "If %s had a soul, it must be very delicious."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WX78.HUGGER = "Wormwood doesn't understand."
STRINGS.CHARACTERS.WURT.DESCRIBE.WX78.HUGGER = "Hugging smooth metal... feels okay, Plorg."
STRINGS.CHARACTERS.WALTER.DESCRIBE.WX78.HUGGER = "Woby, look..."
STRINGS.CHARACTERS.WANDA.DESCRIBE.WX78.HUGGER = "I wonder if %s has a concept of time..."


STRINGS.CHARACTERS.GENERIC.DESCRIBE.WICKERBOTTOM.HUGGER = "Kind Ms. Wickerbottom is providing psychological support to the other person."
--STRINGS.CHARACTERS.WILSON.DESCRIBE.WICKERBOTTOM.HUGGER = ""
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WICKERBOTTOM.HUGGER = "It looks like an old lady comforting a child."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WICKERBOTTOM.HUGGER = "Ms. %s is very kind."
STRINGS.CHARACTERS.WENDY.DESCRIBE.WICKERBOTTOM.HUGGER = "She is so kind to everyone..."
STRINGS.CHARACTERS.WX78.DESCRIBE.WICKERBOTTOM.HUGGER = "What function does this have for organic beings?"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WICKERBOTTOM.HUGGER = "I'm not that old yet to need someone to help me walk."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WICKERBOTTOM.HUGGER = "Ms. %s's manners are impeccable."
--STRINGS.CHARACTERS.WES.DESCRIBE.WICKERBOTTOM.HUGGER = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WICKERBOTTOM.HUGGER = "Dependent on others for everything when you're old, how pitiful."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WICKERBOTTOM.HUGGER = "Ms. %s has wisdom and a heart that warms others, may the gods bless you!"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WICKERBOTTOM.HUGGER = "We used to enjoy hugging grandma as kids."
STRINGS.CHARACTERS.WINONA.DESCRIBE.WICKERBOTTOM.HUGGER = "Such a gentle hug can boost team morale, which is great."
STRINGS.CHARACTERS.WARLY.DESCRIBE.WICKERBOTTOM.HUGGER = "A kind-hearted lady, her warmth is like a warm meal."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.WICKERBOTTOM.HUGGER = "I wonder if she can see through the darkness in my heart."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WICKERBOTTOM.HUGGER = "Her kindness is rare, but I don't need it."
STRINGS.CHARACTERS.WURT.DESCRIBE.WICKERBOTTOM.HUGGER = "Grandma's hugs are always warm, Plorg."
STRINGS.CHARACTERS.WALTER.DESCRIBE.WICKERBOTTOM.HUGGER = "Ms. Wickerbottom's grace and kindness set a fine example for us all."
STRINGS.CHARACTERS.WANDA.DESCRIBE.WICKERBOTTOM.HUGGER = "Her embrace is like a ray of sunshine on a gloomy day."

-------------------------------------------------------------------
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODIE.HUGGER = "The lumberjack %s likes to hug trees, but he also hugs people sometimes."
--STRINGS.CHARACTERS.WILSON.DESCRIBE.WOODIE.HUGGER = ""
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WOODIE.HUGGER = "I hope he doesn't accidentally hug a tree instead of me."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WOODIE.HUGGER = "The strong man needs to control his strength when hugging."
STRINGS.CHARACTERS.WENDY.DESCRIBE.WOODIE.HUGGER = "His hugs are too strong, I might break."
STRINGS.CHARACTERS.WX78.DESCRIBE.WOODIE.HUGGER = "Physical contact is inefficient for energy transfer."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WOODIE.HUGGER = "Mr. Woodie, please be gentle with others."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WOODIE.HUGGER = "Hugging is a way to show affection, whether it's a tree or a person."
--STRINGS.CHARACTERS.WES.DESCRIBE.WOODIE.HUGGER = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WOODIE.HUGGER = "A bit too rough for my tastes."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WOODIE.HUGGER = "A powerful warrior, showing his softer side."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WOODIE.HUGGER = "We prefer hugging soft things, not something so strong."
STRINGS.CHARACTERS.WINONA.DESCRIBE.WOODIE.HUGGER = "His hugs are strong, but they can also boost morale."
STRINGS.CHARACTERS.WARLY.DESCRIBE.WOODIE.HUGGER = "A strong embrace, suitable for both trees and friends."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.WOODIE.HUGGER = "I wonder if he can hug the darkness away."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WOODIE.HUGGER = "Strong hugs, but I don't need them."
STRINGS.CHARACTERS.WURT.DESCRIBE.WOODIE.HUGGER = "Hugging a bear, Plorg."
STRINGS.CHARACTERS.WALTER.DESCRIBE.WOODIE.HUGGER = "Mr. Woodie's strength is admirable, but he must be careful."
STRINGS.CHARACTERS.WANDA.DESCRIBE.WOODIE.HUGGER = "His hugs are strong, but they feel safe."

-------------------------------------------------------------------
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WAXWELL.DESCRIBE = "The gentleman %s believes that hugging is not a proper behavior."
--STRINGS.CHARACTERS.WILSON.DESCRIBE.WAXWELL.DESCRIBE = ""
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WAXWELL.DESCRIBE = "He's so formal, I doubt he even knows how to hug."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WAXWELL.DESCRIBE = "A true gentleman, but a bit too stiff."
STRINGS.CHARACTERS.WENDY.DESCRIBE.WAXWELL.DESCRIBE = "His cold demeanor makes him hard to approach."
STRINGS.CHARACTERS.WX78.DESCRIBE.WAXWELL.DESCRIBE = "Unnecessary physical contact."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WAXWELL.DESCRIBE = "Mr. Waxwell, perhaps a little warmth would do you good."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WAXWELL.DESCRIBE = "He's too uptight, I'd rather hug a tree."
--STRINGS.CHARACTERS.WES.DESCRIBE.WAXWELL.DESCRIBE = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WAXWELL.DESCRIBE = "Gentlemen do not engage in such frivolous behavior."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WAXWELL.DESCRIBE = "A true gentleman, but lacking in warmth."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WAXWELL.DESCRIBE = "We prefer to keep our distance from such formal people."
STRINGS.CHARACTERS.WINONA.DESCRIBE.WAXWELL.DESCRIBE = "His formality can be off-putting, but he means well."
STRINGS.CHARACTERS.WARLY.DESCRIBE.WAXWELL.DESCRIBE = "A gentleman should be polite, but not cold."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.WAXWELL.DESCRIBE = "I wonder if he has a dark side hidden beneath his formal exterior."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WAXWELL.DESCRIBE = "Too formal, I don't need his hugs."
STRINGS.CHARACTERS.WURT.DESCRIBE.WAXWELL.DESCRIBE = "Formal hugs, Plorg."
STRINGS.CHARACTERS.WALTER.DESCRIBE.WAXWELL.DESCRIBE = "Mr. Waxwell's formality is commendable, but a little warmth would be better."
STRINGS.CHARACTERS.WANDA.DESCRIBE.WAXWELL.DESCRIBE = "His formality is admirable, but I prefer a more relaxed approach."

-------------------------------------------------------------------
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WATHGRITHR.HUGGER = "The wise %s uses hugs to build warrior camaraderie."
--STRINGS.CHARACTERS.WILSON.DESCRIBE.WATHGRITHR.HUGGER = ""
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WATHGRITHR.HUGGER = "I bet he's thinking about strategy even while hugging."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WATHGRITHR.HUGGER = "A wise leader, always thinking of the team."
STRINGS.CHARACTERS.WENDY.DESCRIBE.WATHGRITHR.HUGGER = "His hugs are full of wisdom and strength."
STRINGS.CHARACTERS.WX78.DESCRIBE.WATHGRITHR.HUGGER = "Logical behavior for team bonding."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WATHGRITHR.HUGGER = "Mr. Wathgrithr, your wisdom and strength inspire us all."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WATHGRITHR.HUGGER = "He's a great leader, but his hugs are a bit intense."
--STRINGS.CHARACTERS.WES.DESCRIBE.WATHGRITHR.HUGGER = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WATHGRITHR.HUGGER = "A bit too intense for my taste."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WATHGRITHR.HUGGER = "Hugs build trust and camaraderie among warriors."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WATHGRITHR.HUGGER = "We respect his wisdom, but his hugs are a bit too strong."
STRINGS.CHARACTERS.WINONA.DESCRIBE.WATHGRITHR.HUGGER = "His hugs are strong, but they inspire confidence."
STRINGS.CHARACTERS.WARLY.DESCRIBE.WATHGRITHR.HUGGER = "A wise and strong leader, his hugs are a sign of unity."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.WATHGRITHR.HUGGER = "I wonder if he can see through my darkness."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WATHGRITHR.HUGGER = "Strong hugs, but I don't need them."
STRINGS.CHARACTERS.WURT.DESCRIBE.WATHGRITHR.HUGGER = "Strong hugs, Plorg."
STRINGS.CHARACTERS.WALTER.DESCRIBE.WATHGRITHR.HUGGER = "Mr. Wathgrithr's wisdom and strength are invaluable to the team."
STRINGS.CHARACTERS.WANDA.DESCRIBE.WATHGRITHR.HUGGER = "His hugs are strong, but they feel safe and inspiring."

-------------------------------------------------------------------
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WEBBER.HUGGER = "The insectoid %s enjoys hugging those with exaggerated hairstyles."
--STRINGS.CHARACTERS.WILSON.DESCRIBE.WEBBER.HUGGER = ""
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WEBBER.HUGGER = "I bet he's just attracted to the style of the hair."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WEBBER.HUGGER = "A unique preference, but a bit strange."
STRINGS.CHARACTERS.WENDY.DESCRIBE.WEBBER.HUGGER = "His hugs are a bit creepy, but he means well."
STRINGS.CHARACTERS.WX78.DESCRIBE.WEBBER.HUGGER = "Unusual behavior for an insectoid."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WEBBER.HUGGER = "Mr. Webber, perhaps you should focus on more important matters."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WEBBER.HUGGER = "His hugs are a bit strange, but he's harmless."
--STRINGS.CHARACTERS.WES.DESCRIBE.WEBBER.HUGGER = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WEBBER.HUGGER = "A bit too casual for my tastes."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WEBBER.HUGGER = "An unusual preference, but it's his way of showing affection."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WEBBER.HUGGER = "We like to hug those with interesting hair."
STRINGS.CHARACTERS.WINONA.DESCRIBE.WEBBER.HUGGER = "His hugs are a bit strange, but they can be amusing."
STRINGS.CHARACTERS.WARLY.DESCRIBE.WEBBER.HUGGER = "A unique way to show affection, but a bit odd."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.WEBBER.HUGGER = "I wonder if he can hug the darkness away with his strange hugs."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WEBBER.HUGGER = "Strange hugs, but I don't need them."
STRINGS.CHARACTERS.WURT.DESCRIBE.WEBBER.HUGGER = "Strange hugs, Plorg."
STRINGS.CHARACTERS.WALTER.DESCRIBE.WEBBER.HUGGER = "Mr. Webber's unique preferences are part of his charm."
STRINGS.CHARACTERS.WANDA.DESCRIBE.WEBBER.HUGGER = "His hugs are strange, but they can be fun."

-------------------------------------------------------------------
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WINONA.HUGGER = "The engineer %s believes that hugs can improve work efficiency."
--STRINGS.CHARACTERS.WILSON.DESCRIBE.WINONA.HUGGER = ""
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WINONA.HUGGER = "I hope her hugs don't involve any machinery."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WINONA.HUGGER = "A practical approach to teamwork."
STRINGS.CHARACTERS.WENDY.DESCRIBE.WINONA.HUGGER = "Her hugs are efficient, but a bit mechanical."
STRINGS.CHARACTERS.WX78.DESCRIBE.WINONA.HUGGER = "Efficient energy transfer method."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WINONA.HUGGER = "Ms. Winona, your practical approach is commendable."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WINONA.HUGGER = "Her hugs are a bit too efficient, but they get the job done."
--STRINGS.CHARACTERS.WES.DESCRIBE.WINONA.HUGGER = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WINONA.HUGGER = "A bit too mechanical for my tastes."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WINONA.HUGGER = "A practical approach to building team spirit."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WINONA.HUGGER = "We prefer more natural forms of affection."
STRINGS.CHARACTERS.WINONA.DESCRIBE.WINONA.HUGGER = "Hugs can improve work efficiency, which is great."
STRINGS.CHARACTERS.WARLY.DESCRIBE.WINONA.HUGGER = "A practical and efficient approach to team building."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.WINONA.HUGGER = "I wonder if her hugs can fix the darkness in my heart."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WINONA.HUGGER = "Efficient hugs, but I don't need them."
STRINGS.CHARACTERS.WURT.DESCRIBE.WINONA.HUGGER = "Efficient hugs, Plorg."
STRINGS.CHARACTERS.WALTER.DESCRIBE.WINONA.HUGGER = "Ms. Winona's practical approach is commendable."
STRINGS.CHARACTERS.WANDA.DESCRIBE.WINONA.HUGGER = "Her hugs are efficient, but they feel a bit mechanical."

-------------------------------------------------------------------
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WARLY.HUGGER = "The chef %s believes that hugs are a form of sharing love and food."
--STRINGS.CHARACTERS.WILSON.DESCRIBE.WARLY.HUGGER = ""
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WARLY.HUGGER = "I hope his hugs don't come with a side of food."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WARLY.HUGGER = "A warm and caring chef."
STRINGS.CHARACTERS.WENDY.DESCRIBE.WARLY.HUGGER = "His hugs are warm, but I don't want any food with them."
STRINGS.CHARACTERS.WX78.DESCRIBE.WARLY.HUGGER = "Inefficient energy transfer method."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WARLY.HUGGER = "Mr. Warly, your warmth and care are appreciated."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WARLY.HUGGER = "His hugs are warm, but I don't need any food."
--STRINGS.CHARACTERS.WES.DESCRIBE.WARLY.HUGGER = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WARLY.HUGGER = "A bit too informal for my tastes."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WARLY.HUGGER = "A warm and caring chef, but a bit too informal."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WARLY.HUGGER = "We prefer more natural forms of affection."
STRINGS.CHARACTERS.WINONA.DESCRIBE.WARLY.HUGGER = "His hugs are warm, but I don't need any food with them."
STRINGS.CHARACTERS.WARLY.DESCRIBE.WARLY.HUGGER = "Only love and food should not be wasted, this is a very thoughtful move, sir."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.WARLY.HUGGER = "I wonder if his hugs can fix the darkness in my heart."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WARLY.HUGGER = "Warm hugs, but I don't need them."
STRINGS.CHARACTERS.WURT.DESCRIBE.WARLY.HUGGER = "Warm hugs, Plorg."
STRINGS.CHARACTERS.WALTER.DESCRIBE.WARLY.HUGGER = "Mr. Warly's warmth and care are commendable."
STRINGS.CHARACTERS.WANDA.DESCRIBE.WARLY.HUGGER = "His hugs are warm, but they feel a bit too informal."

-------------------------------------------------------------------
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WORTOX.HUGGER = "The dark %s believes that hugs can bring light to the darkness."
--STRINGS.CHARACTERS.WILSON.DESCRIBE.WORTOX.HUGGER = ""
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WORTOX.HUGGER = "I wonder if his hugs can actually bring light to the darkness."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WORTOX.HUGGER = "A mysterious and dark figure."
STRINGS.CHARACTERS.WENDY.DESCRIBE.WORTOX.HUGGER = "His hugs are dark, but I wonder if they can bring light."
STRINGS.CHARACTERS.WX78.DESCRIBE.WORTOX.HUGGER = "Inefficient energy transfer method."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WORTOX.HUGGER = "Mr. Wortox, your mysterious nature is intriguing."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WORTOX.HUGGER = "His hugs are dark, but I wonder if they can bring light."
--STRINGS.CHARACTERS.WES.DESCRIBE.WORTOX.HUGGER = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WORTOX.HUGGER = "A bit too dark for my tastes."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WORTOX.HUGGER = "A mysterious and dark figure, but his hugs may bring light."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WORTOX.HUGGER = "We prefer more natural forms of affection."
STRINGS.CHARACTERS.WINONA.DESCRIBE.WORTOX.HUGGER = "His hugs are dark, but they may bring light."
STRINGS.CHARACTERS.WARLY.DESCRIBE.WORTOX.HUGGER = "A mysterious and dark figure, but his hugs may bring light."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.WORTOX.HUGGER = "I wonder if my hugs can bring light to the darkness."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WORTOX.HUGGER = "Dark hugs, but I don't need them."
STRINGS.CHARACTERS.WURT.DESCRIBE.WORTOX.HUGGER = "Dark hugs, Plorg."
STRINGS.CHARACTERS.WALTER.DESCRIBE.WORTOX.HUGGER = "Mr. Wortox's mysterious nature is intriguing."
STRINGS.CHARACTERS.WANDA.DESCRIBE.WORTOX.HUGGER = "His hugs are dark, but they may bring light."

-------------------------------------------------------------------
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WORMWOOD.HUGGER = "The enigmatic %s does not believe in the power of hugs."
--STRINGS.CHARACTERS.WILSON.DESCRIBE.WORMWOOD.HUGGER = ""
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WORMWOOD.HUGGER = "I doubt he even knows how to hug."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WORMWOOD.HUGGER = "A mysterious and enigmatic figure."
STRINGS.CHARACTERS.WENDY.DESCRIBE.WORMWOOD.HUGGER = "His cold demeanor makes him hard to approach."
STRINGS.CHARACTERS.WX78.DESCRIBE.WORMWOOD.HUGGER = "Unnecessary physical contact."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WORMWOOD.HUGGER = "Mr. Wormwood, perhaps a little warmth would do you good."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WORMWOOD.HUGGER = "He's too cold, I'd rather hug a tree."
--STRINGS.CHARACTERS.WES.DESCRIBE.WORMWOOD.HUGGER = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WORMWOOD.HUGGER = "A bit too cold for my tastes."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WORMWOOD.HUGGER = "A mysterious and enigmatic figure, but lacking in warmth."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WORMWOOD.HUGGER = "We prefer to keep our distance from such cold people."
STRINGS.CHARACTERS.WINONA.DESCRIBE.WORMWOOD.HUGGER = "His cold demeanor can be off-putting, but he means well."
STRINGS.CHARACTERS.WARLY.DESCRIBE.WORMWOOD.HUGGER = "A cold and distant figure, but he has his reasons."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.WORMWOOD.HUGGER = "I wonder if he has a dark side hidden beneath his cold exterior."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WORMWOOD.HUGGER = "Hugs are unnecessary."
STRINGS.CHARACTERS.WURT.DESCRIBE.WORMWOOD.HUGGER = "Cold hugs, Plorg."
STRINGS.CHARACTERS.WALTER.DESCRIBE.WORMWOOD.HUGGER = "Mr. Wormwood's cold demeanor is commendable, but a little warmth would be better."
STRINGS.CHARACTERS.WANDA.DESCRIBE.WORMWOOD.HUGGER = "His cold demeanor is admirable, but I prefer a more relaxed approach."

-------------------------------------------------------------------
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WURT.HUGGER = "The quirky %s enjoys hugging smooth surfaces."
--STRINGS.CHARACTERS.WILSON.DESCRIBE.WURT.HUGGER = ""
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WURT.HUGGER = "I bet he's just attracted to the smoothness."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WURT.HUGGER = "A unique preference, but a bit strange."
STRINGS.CHARACTERS.WENDY.DESCRIBE.WURT.HUGGER = "His hugs are a bit strange, but he means well."
STRINGS.CHARACTERS.WX78.DESCRIBE.WURT.HUGGER = "Unusual behavior for a quirky character."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WURT.HUGGER = "Mr. Wurt, perhaps you should focus on more important matters."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WURT.HUGGER = "His hugs are a bit strange, but he's harmless."
--STRINGS.CHARACTERS.WES.DESCRIBE.WURT.HUGGER = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WURT.HUGGER = "A bit too casual for my tastes."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WURT.HUGGER = "An unusual preference, but it's his way of showing affection."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WURT.HUGGER = "We like to hug smooth surfaces, Plorg."
STRINGS.CHARACTERS.WINONA.DESCRIBE.WURT.HUGGER = "His hugs are a bit strange, but they can be amusing."
STRINGS.CHARACTERS.WARLY.DESCRIBE.WURT.HUGGER = "A unique way to show affection, but a bit odd."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.WURT.HUGGER = "I wonder if he can hug the darkness away with his strange hugs."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WURT.HUGGER = "Strange hugs, but I don't need them."
STRINGS.CHARACTERS.WURT.DESCRIBE.WURT.HUGGER = "Hugging smooth surfaces... feels okay, Plorg."
STRINGS.CHARACTERS.WALTER.DESCRIBE.WURT.HUGGER = "Mr. Wurt's unique preferences are part of his charm."
STRINGS.CHARACTERS.WANDA.DESCRIBE.WURT.HUGGER = "His hugs are strange, but they can be fun."

-------------------------------------------------------------------
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALTER.HUGGER = "The noble %s believes that hugs can restore courage."
--STRINGS.CHARACTERS.WILSON.DESCRIBE.WALTER.HUGGER = ""
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WALTER.HUGGER = "I hope his hugs don't come with any lectures."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WALTER.HUGGER = "A noble and caring figure."
STRINGS.CHARACTERS.WENDY.DESCRIBE.WALTER.HUGGER = "His hugs are noble, but I don't need any lectures with them."
STRINGS.CHARACTERS.WX78.DESCRIBE.WALTER.HUGGER = "Inefficient energy transfer method."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WALTER.HUGGER = "Mr. Walter, your noble intentions are appreciated."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WALTER.HUGGER = "His hugs are noble, but I don't need any lectures."
--STRINGS.CHARACTERS.WES.DESCRIBE.WALTER.HUGGER = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WALTER.HUGGER = "A bit too formal for my tastes."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WALTER.HUGGER = "A noble and caring figure, but a bit too formal."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WALTER.HUGGER = "We prefer more natural forms of affection."
STRINGS.CHARACTERS.WINONA.DESCRIBE.WALTER.HUGGER = "His hugs are noble, but I don't need any lectures."
STRINGS.CHARACTERS.WARLY.DESCRIBE.WALTER.HUGGER = "A noble and caring figure, but a bit too formal."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.WALTER.HUGGER = "I wonder if his hugs can fix the darkness in my heart."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WALTER.HUGGER = "Noble hugs, but I don't need them."
STRINGS.CHARACTERS.WURT.DESCRIBE.WALTER.HUGGER = "Noble hugs, Plorg."
STRINGS.CHARACTERS.WALTER.DESCRIBE.WALTER.HUGGER = "Hugs can restore courage, this is very scientific, sir."
STRINGS.CHARACTERS.WANDA.DESCRIBE.WALTER.HUGGER = "His hugs are noble, but they feel a bit too formal."

-------------------------------------------------------------------
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WANDA.HUGGER = "The kind %s believes that hugs can make people feel better."
--STRINGS.CHARACTERS.WILSON.DESCRIBE.WANDA.HUGGER = ""
STRINGS.CHARACTERS.WILLOW.DESCRIBE.WANDA.HUGGER = "I hope her hugs don't come with any lectures."
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.WANDA.HUGGER = "A kind and caring figure."
STRINGS.CHARACTERS.WENDY.DESCRIBE.WANDA.HUGGER = "Her hugs are kind, but I don't need any lectures."
STRINGS.CHARACTERS.WX78.DESCRIBE.WANDA.HUGGER = "Inefficient energy transfer method."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WANDA.HUGGER = "Ms. Wanda, your kindness is appreciated."
STRINGS.CHARACTERS.WOODIE.DESCRIBE.WANDA.HUGGER = "Her hugs are kind, but I don't need any lectures."
--STRINGS.CHARACTERS.WES.DESCRIBE.WANDA.HUGGER = ""
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.WANDA.HUGGER = "A bit too casual for my tastes."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.WANDA.HUGGER = "A kind and caring figure, but a bit too casual."
STRINGS.CHARACTERS.WEBBER.DESCRIBE.WANDA.HUGGER = "We prefer more natural forms of affection."
STRINGS.CHARACTERS.WINONA.DESCRIBE.WANDA.HUGGER = "Her hugs are kind, but I don't need any lectures."
STRINGS.CHARACTERS.WARLY.DESCRIBE.WANDA.HUGGER = "A kind and caring figure, but a bit too casual."
STRINGS.CHARACTERS.WORTOX.DESCRIBE.WANDA.HUGGER = "I wonder if her hugs can fix the darkness in my heart."
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.WANDA.HUGGER = "Kind hugs, but I don't need them."
STRINGS.CHARACTERS.WURT.DESCRIBE.WANDA.HUGGER = "Kind hugs, Plorg."
STRINGS.CHARACTERS.WALTER.DESCRIBE.WANDA.HUGGER = "Ms. Wanda's kindness is commendable."
STRINGS.CHARACTERS.WANDA.DESCRIBE.WANDA.HUGGER = "Well, it's nice, but please pay attention to others' time."

-------------------------------------------------------------------
